[package]
name = "lambda-calculus-abstract-machine-kn-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
lambda_calculus_abstract_machine_kn = { git = "https://github.com/stfnw/lambda-calculus-abstract-machine-kn.git", rev = "576a2d48f5faeaab1571968b4c5dd7a23bf2b343", version = "0.1.0" }
